### ISSUE TITLE
Grunt issue

### ISSUE THREAD

**Issue by aHumanBeing** [tihomir-kit/sesior#4]
Hi,

Had a few moments to finally dig into your guide and when running RunSPA.sh, I get the following;

./RunSPA.sh: line 2: grunt: command not found

I tried installing grunt manually but this didn't help either.  I am able to start redis, and RunNode.sh currently. 

Any ideas?

Thanks in advance.

**Comment by tihomir-kit** [comment]
On which OS are you running this? If it's windows, you need to add grunt to your PATH env variable.

**Comment by aHumanBeing** [comment]
Ubuntu (trusty tahr)

**Comment by tihomir-kit** [comment]
I'm not sure why it's not working. But the issue here is not in the script. You need to make grunt available through your terminal (if you type in grunt in your terminal, it should recognize the command).

Have you tried something like `npm install grunt`? (you need to have nodejs and npm installed for this to work).

**Comment by aHumanBeing** [comment]
OK thanks.  I'll check on those items again.  Like you said, it should just be available and I believe you when you say it's not the script.
